version: "3"

services:
  counter:
    image: grpcpython
    # command: ["python3.6", "counter/server.py"]
    command: python3.6 main.py --name counter
    # command: sleep 1000000
    # command: while true;do echo "test";sleep 1;done
    ports:
      - "31337"
    deploy:
      replicas: 1
    environment:
      - TERM=xterm

  proxy:
    image: grpcpython
    # command: ["python3.6", "web.py", "proxy", "0.0.0.0", "50002"]
    # command: sleep 1000000
    command: python3.6 main.py --name proxy --upstream counter:31337 --bind 0.0.0.0:50002
    ports:
      - "50002"
    deploy:
      replicas: 4

  frontend:
    image: grpcpython
    # command: ["python3.6", "web.py", "frontend", "0.0.0.0", "50003"]
    # command: sleep 1000000
    command: python3.6 main.py --name frontend --upstream tasks.proxy:50002 --bind 0.0.0.0:8080 --dnslb
    ports:
      - "8080:8080"
    deploy:
      replicas: 2