# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dns.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dns.proto',
  package='dns',
  syntax='proto3',
  serialized_pb=_b('\n\tdns.proto\x12\x03\x64ns\"\x1d\n\x0bInitRequest\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x1e\n\x0cInitResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\")\n\x0bInfoRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\x1e\n\x0cInfoResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x1d\n\x0bHostRequest\x12\x0e\n\x06result\x18\x01 \x01(\x08\"*\n\x0cHostResponse\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\xa9\x01\n\x07\x44NSInfo\x12\x37\n\x0eInitConnection\x12\x10.dns.InitRequest\x1a\x11.dns.InitResponse\"\x00\x12\x31\n\x08InitInfo\x12\x10.dns.InfoRequest\x1a\x11.dns.InfoResponse\"\x00\x12\x32\n\tRoundHost\x12\x10.dns.HostRequest\x1a\x11.dns.HostResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='dns.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dns.InitRequest.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=47,
)


_INITRESPONSE = _descriptor.Descriptor(
  name='InitResponse',
  full_name='dns.InitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dns.InitResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)


_INFOREQUEST = _descriptor.Descriptor(
  name='InfoRequest',
  full_name='dns.InfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='dns.InfoRequest.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='dns.InfoRequest.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=122,
)


_INFORESPONSE = _descriptor.Descriptor(
  name='InfoResponse',
  full_name='dns.InfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dns.InfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=154,
)


_HOSTREQUEST = _descriptor.Descriptor(
  name='HostRequest',
  full_name='dns.HostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='dns.HostRequest.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=185,
)


_HOSTRESPONSE = _descriptor.Descriptor(
  name='HostResponse',
  full_name='dns.HostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='dns.HostResponse.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='dns.HostResponse.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['InitResponse'] = _INITRESPONSE
DESCRIPTOR.message_types_by_name['InfoRequest'] = _INFOREQUEST
DESCRIPTOR.message_types_by_name['InfoResponse'] = _INFORESPONSE
DESCRIPTOR.message_types_by_name['HostRequest'] = _HOSTREQUEST
DESCRIPTOR.message_types_by_name['HostResponse'] = _HOSTRESPONSE

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITREQUEST,
  __module__ = 'dns_pb2'
  # @@protoc_insertion_point(class_scope:dns.InitRequest)
  ))
_sym_db.RegisterMessage(InitRequest)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), dict(
  DESCRIPTOR = _INITRESPONSE,
  __module__ = 'dns_pb2'
  # @@protoc_insertion_point(class_scope:dns.InitResponse)
  ))
_sym_db.RegisterMessage(InitResponse)

InfoRequest = _reflection.GeneratedProtocolMessageType('InfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _INFOREQUEST,
  __module__ = 'dns_pb2'
  # @@protoc_insertion_point(class_scope:dns.InfoRequest)
  ))
_sym_db.RegisterMessage(InfoRequest)

InfoResponse = _reflection.GeneratedProtocolMessageType('InfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _INFORESPONSE,
  __module__ = 'dns_pb2'
  # @@protoc_insertion_point(class_scope:dns.InfoResponse)
  ))
_sym_db.RegisterMessage(InfoResponse)

HostRequest = _reflection.GeneratedProtocolMessageType('HostRequest', (_message.Message,), dict(
  DESCRIPTOR = _HOSTREQUEST,
  __module__ = 'dns_pb2'
  # @@protoc_insertion_point(class_scope:dns.HostRequest)
  ))
_sym_db.RegisterMessage(HostRequest)

HostResponse = _reflection.GeneratedProtocolMessageType('HostResponse', (_message.Message,), dict(
  DESCRIPTOR = _HOSTRESPONSE,
  __module__ = 'dns_pb2'
  # @@protoc_insertion_point(class_scope:dns.HostResponse)
  ))
_sym_db.RegisterMessage(HostResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class DNSInfoStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.InitConnection = channel.unary_unary(
          '/dns.DNSInfo/InitConnection',
          request_serializer=InitRequest.SerializeToString,
          response_deserializer=InitResponse.FromString,
          )
      self.InitInfo = channel.unary_unary(
          '/dns.DNSInfo/InitInfo',
          request_serializer=InfoRequest.SerializeToString,
          response_deserializer=InfoResponse.FromString,
          )
      self.RoundHost = channel.unary_unary(
          '/dns.DNSInfo/RoundHost',
          request_serializer=HostRequest.SerializeToString,
          response_deserializer=HostResponse.FromString,
          )


  class DNSInfoServicer(object):

    def InitConnection(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def InitInfo(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def RoundHost(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DNSInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'InitConnection': grpc.unary_unary_rpc_method_handler(
            servicer.InitConnection,
            request_deserializer=InitRequest.FromString,
            response_serializer=InitResponse.SerializeToString,
        ),
        'InitInfo': grpc.unary_unary_rpc_method_handler(
            servicer.InitInfo,
            request_deserializer=InfoRequest.FromString,
            response_serializer=InfoResponse.SerializeToString,
        ),
        'RoundHost': grpc.unary_unary_rpc_method_handler(
            servicer.RoundHost,
            request_deserializer=HostRequest.FromString,
            response_serializer=HostResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'dns.DNSInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDNSInfoServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def InitConnection(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def InitInfo(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def RoundHost(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDNSInfoStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def InitConnection(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    InitConnection.future = None
    def InitInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    InitInfo.future = None
    def RoundHost(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    RoundHost.future = None


  def beta_create_DNSInfo_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('dns.DNSInfo', 'InitConnection'): InitRequest.FromString,
      ('dns.DNSInfo', 'InitInfo'): InfoRequest.FromString,
      ('dns.DNSInfo', 'RoundHost'): HostRequest.FromString,
    }
    response_serializers = {
      ('dns.DNSInfo', 'InitConnection'): InitResponse.SerializeToString,
      ('dns.DNSInfo', 'InitInfo'): InfoResponse.SerializeToString,
      ('dns.DNSInfo', 'RoundHost'): HostResponse.SerializeToString,
    }
    method_implementations = {
      ('dns.DNSInfo', 'InitConnection'): face_utilities.unary_unary_inline(servicer.InitConnection),
      ('dns.DNSInfo', 'InitInfo'): face_utilities.unary_unary_inline(servicer.InitInfo),
      ('dns.DNSInfo', 'RoundHost'): face_utilities.unary_unary_inline(servicer.RoundHost),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_DNSInfo_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('dns.DNSInfo', 'InitConnection'): InitRequest.SerializeToString,
      ('dns.DNSInfo', 'InitInfo'): InfoRequest.SerializeToString,
      ('dns.DNSInfo', 'RoundHost'): HostRequest.SerializeToString,
    }
    response_deserializers = {
      ('dns.DNSInfo', 'InitConnection'): InitResponse.FromString,
      ('dns.DNSInfo', 'InitInfo'): InfoResponse.FromString,
      ('dns.DNSInfo', 'RoundHost'): HostResponse.FromString,
    }
    cardinalities = {
      'InitConnection': cardinality.Cardinality.UNARY_UNARY,
      'InitInfo': cardinality.Cardinality.UNARY_UNARY,
      'RoundHost': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'dns.DNSInfo', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
